name: panini
favicon: null
layout_spectrum: 0.24486
typography_spectrum: 0.83937
title: PANINI DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.8141047714743763
  saturation: 0.35243300534784794
  rhythmicContrast: 0.22152385115623474
purpose: []
