name: panini
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85504
title: PANINI DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a69871'
    - '#d32064'
    - '#fdfdf5'
    - '#007abd'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
