name: panini
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83937
title: PANINI DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fdfdfd'
    - '#f3fd1e'
    - '#a5a739'
    - '#3b3b3b'
  brandStrength: 0.5
  lightness: 0.8141047714743763
  saturation: 0.35243300534784794
  rhythmicContrast: 0.22152385115623474
purpose: []
