name: panini
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83937
title: PANINI DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#ff00ff'
    - '#3f3f3f'
    - '#a9a9a9'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
